name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda with Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: test-env
        channels: conda-forge

    - name: Install conda dependencies
      shell: bash -el {0}
      run: |
        conda install rdkit numpy scipy matplotlib scikit-learn pandas tabulate tqdm seaborn psutil pyyaml -y
        pip install weasyprint rich rich-argparse packaging requests flake8 pytest
        pip install -e .

    - name: Lint with flake8
      shell: bash -el {0}
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests with pytest
      shell: bash -el {0}
      run: |
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
        pytest
